#!/bin/bash

# Get parent directory
parent_dir=$(dirname $(pwd))

# Copy all HTML files to parent directory, but only if they are newer or do not exist
for file in *.html
do
    if [ ! -f "$parent_dir/$file" ] || [ "$file" -nt "$parent_dir/$file" ]
    then
        cp -u "$file" "$parent_dir"
    fi
done
